name: Build iOS XCFramework

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Kotlin & Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make XCFramework
        run: ./gradlew :composeApp:assembleReleaseXCFramework --stacktrace --info

      - name: Show available Gradle tasks
        run: ./gradlew :composeApp:tasks --all


      - name: Upload XCFramework artifact
        uses: actions/upload-artifact@v4
        with:
          name: ComposeApp.xcframework
          path: composeApp/build/XCFrameworks/release/ComposeApp.xcframework
          
